version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.9.8
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
  redis:
    image: redis:6.2.7
    ports:
      - 6379:6379